### ISSUE TITLE
module 'os' has no attribute 'splice'

### ISSUE THREAD

**Issue by renoproc** [crusoe112/DirtyPipePython#1]
I've an issue with Python 3.7.3...

Traceback (most recent call last):
  File "dirty.py", line 399, in <module>
    main()
  File "dirty.py", line 370, in main
    run_etc_passwd()
  File "dirty.py", line 312, in run_etc_passwd
    run_poc(bytes(data_to_write, 'utf-8'), target_file, file_offset)
  File "dirty.py", line 126, in run_poc
    n = os.splice(
AttributeError: module 'os' has no attribute 'splice'

**Comment by crusoe112** [comment]
This currently only works with Python 3.10, when [splice was added to the OS library](https://docs.python.org/3/library/os.html#os.splice).

I do see this library that exists that says it works for earlier versions of Python: [py-splice](https://pypi.org/project/py-splice/)

Assuming it works, it could be added, but it would probably be best to use it conditionally based on the Python version so that users of Python 3.10 wouldn't need an additional dependency.

**Comment by renoproc** [comment]
Ok, thank you for these precisions.
